# 04 - Business Insights & Executive Report

Final notebook for Phase 1 summarizing analytical findings and business recommendations.

In [1]:
import pandas as pd
df=pd.read_csv(r"/mnt/data/american_bankruptcy.csv")

## Executive Summary

In [2]:
summary=pd.DataFrame({
'Metric':['Total Records','Companies','Years Covered','Alive','Failed'],
'Value':[len(df),
df['company_name'].nunique(),
f"{df['year'].min()}-{df['year'].max()}",
(df['status_label']=='alive').sum(),
(df['status_label']!='alive').sum()]
})
display(summary)

          Metric      Value
0  Total Records      78682
1      Companies       8971
2  Years Covered  1999-2018
3          Alive      73462
4         Failed       5220

## Key Findings

In [3]:
findings=[
'The dataset spans multiple fiscal years, enabling longitudinal analysis.',
'The target variable is imbalanced, requiring appropriate evaluation metrics.',
'Financial variables contain outliers that should be reviewed before preprocessing.',
'Some variables are correlated and may require feature selection.'
]
for i,f in enumerate(findings,1):
    print(f'{i}. {f}')

1. The dataset spans multiple fiscal years, enabling longitudinal analysis.
2. The target variable is imbalanced, requiring appropriate evaluation metrics.
3. Financial variables contain outliers that should be reviewed before preprocessing.
4. Some variables are correlated and may require feature selection.

## Business Implications

In [4]:
implications=[
'Early identification of financially distressed firms can improve lending and investment decisions.',
'Risk models should prioritize Recall, Precision, F1-score, ROC-AUC and PR-AUC.',
'Historical trends can support proactive monitoring strategies.'
]
for i,x in enumerate(implications,1):
    print(f'{i}. {x}')

1. Early identification of financially distressed firms can improve lending and investment decisions.
2. Risk models should prioritize Recall, Precision, F1-score, ROC-AUC and PR-AUC.
3. Historical trends can support proactive monitoring strategies.

## Risks & Limitations

In [5]:
limits=[
'Public historical data may not capture all factors affecting bankruptcy.',
'Class imbalance may bias naive models.',
'Correlation does not imply causation.'
]
for l in limits:
    print('-',l)

- Public historical data may not capture all factors affecting bankruptcy.
- Class imbalance may bias naive models.
- Correlation does not imply causation.

## Recommendations for Phase 2

In [6]:
steps=[
'Encode target labels.',
'Handle class imbalance.',
'Engineer financial features.',
'Scale or transform selected variables.',
'Split data into train/validation/test sets.',
'Develop baseline and advanced ML models.'
]
for s in steps:
    print('→',s)

→ Encode target labels.
→ Handle class imbalance.
→ Engineer financial features.
→ Scale or transform selected variables.
→ Split data into train/validation/test sets.
→ Develop baseline and advanced ML models.

## Phase 1 Completion Checklist

In [7]:
checklist=pd.DataFrame({
'Deliverable':[
'Data Profiling',
'Data Quality Assessment',
'Univariate EDA',
'Bivariate EDA',
'Correlation & Outlier Analysis',
'Time Trend Analysis',
'Business Insights'],
'Status':['Complete']*7})
display(checklist)

                      Deliverable    Status
0                  Data Profiling  Complete
1         Data Quality Assessment  Complete
2                  Univariate EDA  Complete
3                   Bivariate EDA  Complete
4  Correlation & Outlier Analysis  Complete
5             Time Trend Analysis  Complete
6               Business Insights  Complete